# Configuration g√©n√©rale
baseURL: "https://nicolassaint.fr/"
publishDir: "docs"
relativeURLs: false
canonifyURLs: true
theme: PaperMod

# Configuration multilingue
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

languages:
  en:
    contentDir: "content/english"
    languageCode: "en-us"
    languageName: "English"
    weight: 1
    title: "Nicolas Saint"
    params:
      profileMode:
        enabled: true
        title: "Nicolas Saint"
        subtitle: "Hi üëã I'm Nicolas, a tech and open-source AI ü§ó enthusiast passionate about solving complex problems. As a Data Science intern at the [**Ministry of Economy and Finance**](https://www.economie.gouv.fr/), I'm developing robust, sovereign, and privacy-focused AI tools (chatbots, RAG systems, summarization tools...) for the French government using state-of-the-art open-source models."
        imageUrl: "home/nicolassaint-london.jpg"
        imageWidth: 220
        imageHeight: 220
        buttons:
          - name: "Resume"
            url: "https://drive.google.com/file/d/1tIEjer-gTrKwKipt7h65y3tN4NgUV09d/view"
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: education
          name: Education
          url: /education/
          weight: 35
        - identifier: experience
          name: Experience
          url: /experience/
          weight: 40
        - identifier: projects
          name: Projects
          url: /projects
          weight: 45
        - identifier: chat
          name: Chat
          url: /chat/
          weight: 50
        - identifier: search
          name: Search
          url: /en/search
          weight: 55

  fr:
    contentDir: "content/french"
    languageCode: "fr-fr"
    languageName: "Fran√ßais"
    weight: 2
    title: "Nicolas Saint"
    params:
      profileMode:
        enabled: true
        title: "Nicolas Saint"
        subtitle: "Bonjour üëã Je suis Nicolas, un passionn√© de technologie et d'IA open-source ü§ó, enthousiaste √† l'id√©e de r√©soudre des probl√®mes complexes. En tant que stagiaire Data Scientist au [**Minist√®re de l'√âconomie et des Finances**](https://www.economie.gouv.fr/), je d√©veloppe des outils d'IA robustes, souverains et respectueux des donn√©es priv√©es (chatbots, syst√®mes RAG, outils de r√©sum√©...) pour le gouvernement fran√ßais en utilisant des mod√®les open-source √† l'√©tat de l'art."
        imageUrl: "home/nicolassaint-london.jpg"
        imageWidth: 220
        imageHeight: 220
        buttons:
          - name: "CV"
            url: "https://drive.google.com/file/d/1tIEjer-gTrKwKipt7h65y3tN4NgUV09d/view"
    menu:
      main:
        - identifier: home
          name: Accueil
          url: /
          weight: 10
        - identifier: education
          name: Formation
          url: /education/
          weight: 35
        - identifier: experience
          name: Exp√©rience
          url: /experience/
          weight: 40
        - identifier: projects
          name: Projets
          url: /projects
          weight: 45
        - identifier: chat
          name: Chat
          url: /chat/
          weight: 50
        - identifier: search
          name: Recherche
          url: /fr/recherche
          weight: 55

# Param√®tres communs
params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nicolas Saint"
    subtitle: Hi üëã I‚Äôm Nicolas, a tech and open-source AI ü§ó enthusiast passionate about solving complex problems. As a Data Science intern at the [**Ministry of Economy and Finance**](https://www.economie.gouv.fr/), I‚Äôm developing robust, sovereign, and privacy-focused AI tools (chatbots, RAG systems, summarization tools...) for the French government using state-of-the-art open-source models.


    imageUrl: "home/nicolassaint-london.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1tIEjer-gTrKwKipt7h65y3tN4NgUV09d/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nicolas.saint@polytechnique.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nicolas-saint"
    - name: "github"
      url: "https://github.com/nicolassaint"

  customCSS:
    - "css/social-icons.css"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # Add the API configuration
  api:
    endpoint: "https://api.olympia.bhub.cloud/generate"
    model: "llama3.1"
    temperature: 0.7
    stream: false

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
